/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.Kursus;

public class FormPendaftaranAwal extends javax.swing.JFrame {

    /**
     * Creates new form FormPendaftaranAwal
     */
    public FormPendaftaranAwal() {
        initComponents();
        getRootPane().setDefaultButton(btnProses);

        // Batas minimum menjaga form tetap nyaman saat window diperkecil.
        setMinimumSize(new java.awt.Dimension(700, 520));

        // Ukuran awal yang nyaman. Saat di-maximize, GroupLayout akan menyesuaikan.
        setSize(new java.awt.Dimension(900, 560));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtBiaya = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbKursus = new javax.swing.JComboBox<>();
        btnProses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHasil = new javax.swing.JTextArea();
        btnReset = new javax.swing.JButton();
        txtDiskon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Nama");
        jLabel4.setMaximumSize(new java.awt.Dimension(155, 14));
        jLabel4.setMinimumSize(new java.awt.Dimension(155, 14));

        txtNama.setDisabledTextColor(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Biaya");
        jLabel5.setMaximumSize(new java.awt.Dimension(155, 14));
        jLabel5.setMinimumSize(new java.awt.Dimension(155, 14));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Jumlah");
        jLabel6.setMaximumSize(new java.awt.Dimension(155, 14));
        jLabel6.setMinimumSize(new java.awt.Dimension(155, 14));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Pilih Kursus");
        jLabel7.setMaximumSize(new java.awt.Dimension(155, 14));
        jLabel7.setMinimumSize(new java.awt.Dimension(155, 14));

        cmbKursus.setBackground(new java.awt.Color(204, 204, 204));
        cmbKursus.setForeground(java.awt.SystemColor.activeCaptionBorder);
        cmbKursus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Java", "Data Science", "UI/UX" }));
        cmbKursus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKursusActionPerformed(evt);
            }
        });

        btnProses.setBackground(new java.awt.Color(255, 255, 255));
        btnProses.setText("PROSES");
        btnProses.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        txtHasil.setColumns(20);
        txtHasil.setRows(5);
        jScrollPane1.setViewportView(txtHasil);

        btnReset.setBackground(new java.awt.Color(255, 255, 255));
        btnReset.setText("RESET");
        btnReset.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        txtDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiskonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Diskon");
        jLabel8.setMaximumSize(new java.awt.Dimension(155, 14));
        jLabel8.setMinimumSize(new java.awt.Dimension(155, 14));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("FROM PENDAFTARAN");
        jLabel1.setMaximumSize(new java.awt.Dimension(155, 14));
        jLabel1.setMinimumSize(new java.awt.Dimension(155, 14));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnProses, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDiskon)
                                    .addComponent(cmbKursus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtBiaya)
                                    .addComponent(txtJumlah))))))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbKursus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProses, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbKursusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKursusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKursusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
            // Mereset semua form inputan
    txtNama.setText("");
    txtBiaya.setText("");
    txtJumlah.setText("");
    
    // Mengembalikan pilihan kursus ke indeks pertama (default)
    if (cmbKursus.getItemCount() > 0) {
        cmbKursus.setSelectedIndex(0);
    }
    
    // Mengosongkan text area hasil
    txtHasil.setText("");
    
    // Mengembalikan kursor fokus ke inputan nama kembali
    txtNama.requestFocus();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
    //AMBIL DATA INPUTAN DARI FORM
    String namaPendaftar = txtNama.getText().trim();
    String kursusPilihan = cmbKursus.getSelectedItem().toString();
    
    // Menentukan Kode Kursus & Level Otomatis untuk pembuatan objek Kursus (OOP)
    String kodeKursus = "";
    String levelKursus = "Reguler"; 
    
    if (kursusPilihan.equalsIgnoreCase("Java")) {
        kodeKursus = "JV-01";
    } else if (kursusPilihan.equalsIgnoreCase("Data Science")) {
        kodeKursus = "DS-02";
    } else if (kursusPilihan.equalsIgnoreCase("UI/UX")) {
        kodeKursus = "UI-03";
    }

    // Validasi jika nama belum diisi
    if (namaPendaftar.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Nama pendaftar tidak boleh kosong!", 
            "Validasi Gagal", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        //AMBIL DAN VALIDASI ANGKA INPUTAN
        double biayaSesi = Double.parseDouble(txtBiaya.getText().trim());
        int jumlahSesi = Integer.parseInt(txtJumlah.getText().trim());
        double persenDiskon = Double.parseDouble(txtDiskon.getText().trim());
        
        if (biayaSesi < 0 || jumlahSesi < 0 || persenDiskon < 0) {
            throw new NumberFormatException();
        }

        // INTEGRASI OOP & RUMUS MATEMATIKA DISKON
        model.Kursus kursus = new model.Kursus(kodeKursus, kursusPilihan, levelKursus, biayaSesi);
        
        // Menghitung total kotor (Biaya x Jumlah Pertemuan)
        double totalKotor = biayaSesi * jumlahSesi;
        
        // Menghitung besaran nominal potongan dari persen diskon
        double nominalDiskon = totalKotor * (persenDiskon / 100);
        
        // Total akhir setelah dipotong diskon
        double totalAkhir = totalKotor - nominalDiskon;

        // Memformat uang Rupiah (Rp) agar rapi
        java.text.NumberFormat rupiahFormat = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id", "ID"));
        String formatBiaya = rupiahFormat.format(biayaSesi);
        String formatDiskon = rupiahFormat.format(nominalDiskon);
        String formatTotal = rupiahFormat.format(totalAkhir);

        // 4. MENCETAK HASIL PERBAIKAN KE TEXT AREA (txtHasil)
        txtHasil.setText(
            "==================================================\n" +
            "                HASIL PENDAFTARAN                 \n" +
            "==================================================\n" +
            " Nama Lengkap    : " + namaPendaftar + "\n" +
            " Kursus Pilihan  : " + kursusPilihan + " (" + kodeKursus + ")\n" +
            " Biaya Per Sesi  : " + formatBiaya + "\n" +
            " Jumlah Sesi     : " + jumlahSesi + "x pertemuan\n" +
            " Potongan Diskon : " + persenDiskon + "% (" + formatDiskon + ")\n" +
            "--------------------------------------------------\n" +
            " TOTAL BIAYA     : " + formatTotal + "\n" +
            "=================================================="
        );

        // 5. MEMBUAT POP-UP NOTIFIKASI HTML YANG CANTIK
        String pesanHtml = "<html>"
            + "<body style='font-family: Segoe UI, sans-serif; font-size: 12px; color: #333333; padding: 10px;'>"
            + "  <h3 style='color: #007BFF; margin-bottom: 15px; border-bottom: 2px solid #007BFF; padding-bottom: 5px; text-align: center;'>"
            + "     SUCCESS! DATA BERHASIL DI-PROSES"
            + "  </h3>"
            + "  <table style='width: 100%; border-collapse: collapse;'>"
            + "    <tr><td style='padding: 4px 0; font-weight: bold; width: 120px;'>Nama Lengkap</td><td style='color: #555555;'>: " + namaPendaftar + "</td></tr>"
            + "    <tr><td style='padding: 4px 0; font-weight: bold;'>Kursus Pilihan</td><td style='color: #555555;'>: " + kursusPilihan + "</td></tr>"
            + "    <tr><td style='padding: 4px 0; font-weight: bold;'>Biaya Per Sesi</td><td style='color: #555555;'>: " + formatBiaya + "</td></tr>"
            + "    <tr><td style='padding: 4px 0; font-weight: bold;'>Jumlah Sesi</td><td style='color: #555555;'>: " + jumlahSesi + "x pertemuan</td></tr>"
            + "    <tr><td style='padding: 4px 0; font-weight: bold;'>Diskon</td><td style='color: #D32F2F;'>: " + persenDiskon + "% (" + formatDiskon + ")</td></tr>"
            + "    <tr style='border-top: 1px dashed #cccccc;'>"
            + "        <td style='padding: 8px 0; font-weight: bold; font-size: 14px; color: #2E7D32;'>TOTAL BIAYA</td>"
            + "        <td style='padding: 8px 0; font-weight: bold; font-size: 14px; color: #2E7D32;'>: " + formatTotal + "</td>"
            + "    </tr>"
            + "  </table>"
            + "</body>"
            + "</html>";

        // Memunculkan pop-up info sukses
        javax.swing.JOptionPane.showMessageDialog(this, 
            pesanHtml, 
            "Pendaftaran Berhasil", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Masukkan angka biaya, jumlah, dan diskon dengan benar!", 
            "Format Input Salah", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnProsesActionPerformed

    private void txtDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiskonActionPerformed
          // 1. Ambil data inputan dasar
    String namaPendaftar = txtNama.getText().trim();
    String kursusPilihan = cmbKursus.getSelectedItem().toString();

    try {
        // 2. Ambil angka perhitungan
        double biayaSesi = Double.parseDouble(txtBiaya.getText().trim());
        int jumlahSesi = Integer.parseInt(txtJumlah.getText().trim());
        double persenDiskon = Double.parseDouble(txtDiskon.getText().trim());

        // 3. Kalkulasi total akhir
        double totalKotor = biayaSesi * jumlahSesi;
        double nominalDiskon = totalKotor * (persenDiskon / 100);
        double totalAkhir = totalKotor - nominalDiskon;

        // 4. Format mata uang Rupiah
        java.text.NumberFormat rupiahFormat = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id", "ID"));
        
        // 5. Cetak kilat ke text area txtHasil
        txtHasil.setText(
            "==================================================\n" +
            "            PREVIEW HITUNG CEPAT (ENTER)          \n" +
            "==================================================\n" +
            " Nama Pendaftar  : " + namaPendaftar + "\n" +
            " Kursus Pilihan  : " + kursusPilihan + "\n" +
            " Biaya Per Sesi  : " + rupiahFormat.format(biayaSesi) + "\n" +
            " Jumlah Sesi     : " + jumlahSesi + "x pertemuan\n" +
            " Diskon (%)      : " + persenDiskon + "% (" + rupiahFormat.format(nominalDiskon) + ")\n" +
            "--------------------------------------------------\n" +
            " ESTIMASI TOTAL  : " + rupiahFormat.format(totalAkhir) + "\n" +
            "=================================================="
        );

    } catch (NumberFormatException e) {
        txtHasil.setText("Format angka biaya, jumlah, atau diskon belum valid.");
    }
    }//GEN-LAST:event_txtDiskonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPendaftaranAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPendaftaranAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPendaftaranAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPendaftaranAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPendaftaranAwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cmbKursus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBiaya;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextArea txtHasil;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
